### ISSUE TITLE
1.5 docs checklist

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#1869]
## API changes, must fix for 1.5

(see https://github.com/pachyderm/pachyderm/issues/1872)

- [x] scrub for inconsistencies with `inputs` to `input` https://github.com/pachyderm/pachyderm/issues/1811
- [x] scrub for inconsistencies with `stopped` to `killed`
- [x] `atom`, `cross`, and `union` explanations along with scrubbing for inconsistencies https://github.com/pachyderm/pachyderm/issues/1276, https://github.com/pachyderm/pachyderm/issues/1129

## High priority fixes, additions, modifications

- [ ] Add dynamic provisioning examples and test them. https://github.com/pachyderm/pachyderm/issues/1477
- [ ] Explain splitting files, delimiters, with an example https://github.com/pachyderm/pachyderm/issues/1770, https://github.com/pachyderm/pachyderm/issues/1448
- [x] Standardize GPU docs, cookbook to match the format of the rest of the cookbook docs.
- [x] Update Tensorflow/Neon example to reference GPU docs and demonstrate
- [x] Standardize best practices, rearrange structure https://github.com/pachyderm/pachyderm/issues/1269
- [x] Update "client" docs from just Go, to emphasize other languages
- [x] Make sure the we mention vendoring issues somewhere in relation to the Go doc (i.e., that you need a specific version of grpc)
- [ ] Update fruit stand and scraper examples and add back in
- [ ] Openshift deploy corrections and update, https://github.com/pachyderm/pachyderm/issues/1865
- [ ] broken links (e.g., PFS/PPS doc references): https://github.com/pachyderm/pachyderm/issues/1769, https://github.com/pachyderm/pachyderm/issues/1489
- [ ] Update beginner tutorial/demo docs for the montage, https://github.com/pachyderm/pachyderm/issues/1852, https://github.com/pachyderm/pachyderm/issues/1439
- [ ] scrub pachctl docs for formatting issues https://github.com/pachyderm/pachyderm/issues/1437
- [ ] `GlobFile`.
- [ ] "LocationConstraint" issue in AWS deploy docs
- [ ] Add instruction to clone repo to the Azure docs
- [ ] clarify/update `from_commit` docs https://github.com/pachyderm/pachyderm/issues/1737#issuecomment-310505750

## Lower priority fixes, additions, modifications

- [ ] add scale up info to best practices (replicas, parallelism) https://github.com/pachyderm/pachyderm/issues/654, https://github.com/pachyderm/pachyderm/issues/653, https://github.com/pachyderm/pachyderm/pull/1667
- [ ] add logging, monitoring best practices https://github.com/pachyderm/pachyderm/issues/1264, https://github.com/pachyderm/pachyderm/issues/689
- [ ] example put-file from PFS to PFS
- [ ] clarity around port-forward issues and options https://github.com/pachyderm/pachyderm/issues/1440
- [ ] more clarity around put-file options https://github.com/pachyderm/pachyderm/issues/1718, https://github.com/pachyderm/pachyderm/issues/1429, https://github.com/pachyderm/pachyderm/issues/1416, https://github.com/pachyderm/pachyderm/issues/981
- [ ] Modify and add back in the PPS and PFS reference docs.  Also test/fix the included links.
- [ ] Links for the subsection of the Bill of Rights.
- [ ] Update the bill of rights to make sure everything rings true with 1.4.  Also correcting typos along the way.
- [ ] More complete OpenStack deploy docs
- [ ] pipeline/pachyderm "management" docs around deleting repos, pipelines, branches, etc.
- [ ] Update and add back in FAQ
- [ ] more clarity around Docker CMD, entrypoints, etc. https://github.com/pachyderm/pachyderm/issues/1301
- [ ] docs for contributors, including how to deploy a custom build https://github.com/pachyderm/pachyderm/issues/1279, https://github.com/pachyderm/pachyderm/issues/691
- [ ] talk about jobs? https://github.com/pachyderm/pachyderm/issues/655
- [ ] make godoc examples run: https://github.com/pachyderm/pachyderm/issues/376

## Cookbooks

- [ ] distributed joins https://github.com/pachyderm/pachyderm/issues/1490
- [ ] streaming (also for the YC post)
- [ ] Jupyter
- [ ] SQL/database integration https://github.com/pachyderm/pachyderm/issues/657
- [ ] private Docker registry https://github.com/pachyderm/pachyderm/issues/1226

**Comment by gabrielgrant** [comment]
From https://github.com/pachyderm/pachyderm/issues/1885#issuecomment-305388705 : 

 "Append semantics are not documented anywhere and there is no list of formats that support mutation in Pachyderm"

**Comment by gabrielgrant** [comment]
#1894

**Comment by dwhitena** [comment]
Ported to https://github.com/pachyderm/pachyderm/issues/2224.  Closing this.
