### ISSUE TITLE
Authn and Authz for Pachyderm 1.6

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#2153]
This issue is an extension of https://github.com/pachyderm/pachyderm/issues/2024, but with an emphasis on features that we hope to implement for Pachyderm 1.6

There are essentially 4 categories of goals

# Required for launch (launch-blocking)

## Activating/Deactivating
- [x] It must be possible to deactivate auth in a pachyderm cluster
- [x] When a Pachyderm user's paid token expires, we must deactivate auth in their cluster
  - *Note*: We don't deactivate auth, but we do put the cluster in a state where only admins can do anything (and to restore their cluster to a non-enterprise state, an admin must disable auth explicitly). See the design below

When a user's paid token expires while auth is enabled in their cluster, we must not expose their private data.

The current design for deactivation is:
  * All repos become accessible only to cluster admins
  * Admins have all privileges, including adding and removing admins, seeing any data in the cluster, creating/running pipelines, and disabling auth (which will disable Pachyderm authentication and authorization completely, exposing all data)
  * Pipelines continue to run, but as admins—similar to how they run if they were created before auth was enabled. This means that pipelines keep running, but only cluster admins can access their results
  * Non-admins can't do anything. All operations return `access denied`, and in the UI, all repos are rendered as inaccessible
  * This way, private data will not be exposed, and the cluster will continue to operate, but users will not have fine-grained access control. The "moderator" list becomes a single ACL for the whole cluster.
  * This is similar to the state of the cluster before auth is enabled, except instead of giving full access to anyone who has access to kubernetes, pachyderm gives full access to moderators

## UI
- [x] Pachd needs an enterprise token API that lets the caller provide an enterprise token and subsequently check its state (present, absent, or expired) 
- [x] The UI must be able to receive error messages from pachd -- [issue here](https://github.com/pachyderm/dash/issues/99)
  * *Why*: in its initial call to ListRepo, the UI must detect if the call failed because the current user is not logged in, so it can display a login screen
- [x] The UI must have a login screen - [issue here](https://github.com/pachyderm/dash/issues/101)
- [x] The UI must be able to store a user's Pachyderm token as a cookie, and send it to Pachd via the GRPC side-channel after they log in -- [issue here](https://github.com/pachyderm/dash/issues/102)
- [x] The UI needs a new icon and panel for repos to which the user doesn't have access (indicated by the initial ListRepo response) -- [issue here](https://github.com/pachyderm/dash/issues/103)

## Security
- [x] Figure out how to avoid exposing users' S3 credentials to anyone with direct access to their kubernetes cluster. Keep S3 credentials private to Pachyderm, so that users can't circumvent GetFile to see repo data

# Important but not launch-blocking

## UI
- [x] If a customer has already provided a paid token through the UI, they shouldn't have to provide it again when activating auth

## Consistency
* Currently, because auth is a separate service from PFS and PPS, internal consistency issues can arise when e.g. a user tries to create a repo R and an ACL to protect R, but the creation of one of those two objects fails while the other succeeds
* To avoid this, parts of the auth system should be inlined into PFS and PPS
  - ~~[ ]`CreateRepo` must be able to create a repo and its ACL in the same transaction~~
    - Consistency between ACLs and repos has been ensured, but not by sharing a transaction between PFS and Auth. Instead, `CreateRepo` creates an ACL in Auth before creating the PFS Repo itself. If the Repo creation fails, auth will be storing a floating ACL. While this wastes a few bytes, the auth check in `CreateAcl` allows any user to make themselves the owner of a Repo that doesn't exist, so any subsequent call to `CreateRepo` for the same repo will overwrite the old ACL and succeed.
    - This isn't ideal, as a malicious user could issue `CreateACL` calls that race with `CreateRepo`, but at least Pachyderm won't end up in an inconsistent state
  - ~~[ ] `CreatePipeline` must be able to create a capability token for the user and revoke the capability of the pipeline's previous RunAs user in the same transaction~~
    - It's not clear to me why this was needed. The caller of `CreatePipeline` can simply create a new capability token for themselves and update the pipeline to use the new token (a pipeline's capability token is stored in the `PipelineInfo`)

## Security
- [ ] Right now, the object store API does no ACL checks, but is exposed externally (because it's hosted on the same port as the PFS and PPS APIs)
  - `BuildCommit` also does no ACL checks (along with `GetCapability`, `RevokeToken` and a few other API endpoints)
- [ ] We need to support authentication via LDAP, for customers that already have LDAP systems set up
- [ ] TLS authentication between pachd and pachctl (and the dash). Right now all internal traffic is unencrypted
- [ ] Create a guide to using Kubernetes's RBAC features with Pachyerm

**Comment by msteffen** [comment]
One design issue I've encountered: If a user U owns a pipeline P, and U's access to P's input is revoked, what should happen?

If we want to fail the job, we also need to decide if we want to create a stats commit for the failing job (this might be difficult if U's write access to the output repo has also been revoked). Even writing a jobInfo to etcd might be tough, since the jobInfo contains e.g. the parent commit, and if the pipeline's read access to the input repo has been revoked, then it doesn't have access to that info

For now, pipelines will crashloop until their access to the input repo is restored.

**Comment by jdoliner** [comment]
I think most of the things here are worth doing before 1.6 release with a few exceptions:

> BuildCommit also does no ACL checks (along with GetCapability, RevokeToken and a few other API endpoints)

Since BuildCommit is a write we could conceivably skip it since it can't leak any data.

 > Create a guide to using Kubernetes's RBAC features with Pachyerm

This seems like it might entail some integration code in addition to docs. Probably shouldn't block release on it.

> Figure out how to avoid exposing users' S3 credentials to anyone with direct access to their kubernetes cluster. Keep S3 credentials private to Pachyderm, so that users can't circumvent GetFile to see repo data

Has this changed as part of 1.6? I guess we're starting to have actual security guarantees so that's a change. I'm not 100% how we'd secure creds from people who have access to kubernetes. I think it might make sense for this release to assume that k8s still needs to be locked down for pachyderm to be secure and then handle this in the next release.

> We need to support authentication via LDAP, for customers that already have LDAP systems set up
This is valuable but I think not needed for this release. We'll hopefully be working with customers to get this implemented in 1.7.

**Comment by msteffen** [comment]
Two other design notes:
* For 1.6, depending on what we hear from our current customer, we think a "good enough" solution for preventing unauthorized users from accessing data directly in S3 with S3 credentials is: tell customers to only give k8s access to cluster admins.
  * To do this, we need to make sure Pachyderm is usable without k8s access. In particular, we need to make sure that the dash is accessible without `pachctl port-forward`

* Right now, I've solved the Repo/ACL consistency problem (users may have repos with no ACLs) by changing how CreateRepo/CreatePipeline work. Now, those calls may fail if creating the ACL fails, but if the call creates a repo successfully, the new repo will have an appropriate ACL. We may leak ACLs with this solution, but the only cost associated with that is a few bytes of storage space in etcd

**Comment by msteffen** [comment]
I'm closing this issue because 1.6 has launched. Some of the non-launch-blocking issues will be moved into their own GitHub issues
