### ISSUE TITLE
1.6 docs checklist

### ISSUE THREAD

**Issue by dwhitena** [pachyderm/pachyderm#2224]
## API changes, must fix for 1.6

- [x] Auth docs
- [x] Stats docs

## High priority fixes, additions, modifications

- [ ] List permission needed by pachyderm in k8s (serviceaccounts etc.) for kops and otherwise, https://github.com/pachyderm/pachyderm/issues/2052
- [x] Add dynamic provisioning examples and test them. https://github.com/pachyderm/pachyderm/issues/1477, https://github.com/pachyderm/pachyderm/issues/2184
- [ ] Check Azure docs, https://github.com/pachyderm/pachyderm/issues/2254
- [ ] Update fruit stand and scraper examples and add back in
- [ ] Openshift deploy corrections and update, https://github.com/pachyderm/pachyderm/issues/1865
- [x] broken links (e.g., PFS/PPS doc references): https://github.com/pachyderm/pachyderm/issues/1769, https://github.com/pachyderm/pachyderm/issues/1489
- [x] Update beginner tutorial/demo docs for the montage, https://github.com/pachyderm/pachyderm/issues/1852, https://github.com/pachyderm/pachyderm/issues/1439
- [ ] `GlobFile`.
- [x] "LocationConstraint" issue in AWS deploy docs
- [ ] Add instruction to clone repo to the Azure docs
- [ ] clarify/update `from_commit` docs https://github.com/pachyderm/pachyderm/issues/1737#issuecomment-310505750
- [ ] clarify append semantics https://github.com/pachyderm/pachyderm/issues/1885#issuecomment-305388705
- [ ] troubleshooting invalid image and other stuck pipelines: https://github.com/pachyderm/pachyderm/issues/2214, https://github.com/pachyderm/pachyderm/issues/2163,
https://github.com/pachyderm/pachyderm/issues/2053
- [ ] GPU library clarifications: https://github.com/pachyderm/pachyderm/issues/2194
- [ ] egress options and example: https://github.com/pachyderm/pachyderm/issues/1718
- [x] update version numbers in deploy docs and make sure that the outputs are consistent with the latest versions of things.
- [ ] env var of input datums - https://github.com/pachyderm/pachyderm/issues/2232#issuecomment-336726463

## Lower priority fixes, additions, modifications

- [ ] build pachctl from scratch
- [ ] add scale up info to best practices (replicas, parallelism) https://github.com/pachyderm/pachyderm/issues/654, https://github.com/pachyderm/pachyderm/issues/653, https://github.com/pachyderm/pachyderm/pull/1667
- [ ] add logging, monitoring best practices https://github.com/pachyderm/pachyderm/issues/1264, https://github.com/pachyderm/pachyderm/issues/689
- [ ] example put-file from PFS to PFS
- [ ] clarity around port-forward issues and options https://github.com/pachyderm/pachyderm/issues/1440
- [ ] more clarity around put-file options https://github.com/pachyderm/pachyderm/issues/1718, https://github.com/pachyderm/pachyderm/issues/1429, https://github.com/pachyderm/pachyderm/issues/1416, https://github.com/pachyderm/pachyderm/issues/981
- [ ] Modify and add back in the PPS and PFS reference docs.  Also test/fix the included links.
- [ ] Links for the subsection of the Bill of Rights.
- [ ] Update the bill of rights to make sure everything rings true with 1.6.  Also correcting typos along the way.
- [ ] More complete OpenStack deploy docs
- [ ] pipeline/pachyderm "management" docs around deleting repos, pipelines, branches, etc.
- [ ] Update and add back in FAQ
- [ ] more clarity around Docker CMD, entrypoints, etc. https://github.com/pachyderm/pachyderm/issues/1301
- [ ] docs for contributors, including how to deploy a custom build https://github.com/pachyderm/pachyderm/issues/1279, https://github.com/pachyderm/pachyderm/issues/691
- [ ] talk about jobs? https://github.com/pachyderm/pachyderm/issues/655
- [ ] make godoc examples run: https://github.com/pachyderm/pachyderm/issues/376

## Cookbooks

- [ ] incremental https://github.com/pachyderm/pachyderm/issues/1894
- [ ] Using things like Jupyter
- [ ] SQL/database integration https://github.com/pachyderm/pachyderm/issues/657
- [ ] private Docker registry https://github.com/pachyderm/pachyderm/issues/1226
- [ ] levering provenance https://github.com/pachyderm/pachyderm/issues/1489
- [ ] cron

**Comment by sjezewski** [comment]
Closing as 1.6 is done. Dan is going to transfer over the checklist for 1.7
