### ISSUE TITLE
TFJob in Pipeline Spec

### ISSUE THREAD

**Issue by msteffen** [pachyderm/pachyderm#4054]
As part of our current goal to integrate Pachyderm and Kubeflow, we'd like to add supports to placing TFJobs directly in Pachyderm pipeline specs. This is still a high-level exploration, but the tasks that I currently see are:
- [ ] Allow pipeline specs to be written in YAML. This seems feasible by replacing our current parser with https://github.com/go-yaml/yaml
- [ ] Add an unstructured field for TFJobs to our pipeline spec and job spec (validating it will initially consist of checking that either `transform` or `TFJob` is set
- [ ] Modify our standby/resume logic so that for TFJob pipelines, it creates a new TFJob instead of a new RC

**TODO**: Figure out getting TFJob data back into Pachyderm

**Comment by jdoliner** [comment]
Overall this seems like a nicely scoped down approach. The only thing that isn't discussed here that will need to be figured out for an mvp of this is how tfjob is getting access to the data. The simple answer is through the s3gateway, but the tricky part is telling it which commits to access. You can't have it access the `master` branches directly, because those can change between when the job gets triggered and when it starts to run (or while it's running) so we need to point it at static commits, however that means that the TFJob spec needs to be slightly different each time, to reference different commits, or the s3gateway needs to be extended so that it can be setup to give a view into pfs that only exposes the input repos and only at the commits that are supposed to be processed. 

 
A few other thoughts on this: it seems like most of kubeflow is written in jsonnet, although TFjobs (at least the ones I've submitted) were in yaml. Does using jsonnet for pipelines hold any fruit for us long term? It might potentially be an solution to the issue discussed above if we wanted to template the tfjobs on the commits they're processing.

It seems potentially interesting to me to store the tfjob spec as a separate file in the spec commit, rather than embedding it. I don't see any super compelling reason to do it now, but thinking about this long term, I foresee a world where we have a bunch of different files that can be embedded in a pipeline spec (tfjob, sparkjob, the existing stdin field is already an example) and having them as separate files in the filesystem seems just a little bit cleaner to me.

**Comment by msteffen** [comment]
YAML support added by: https://github.com/pachyderm/pachyderm/pull/4078
