### ISSUE TITLE
Tracking issue for 2.0 default

### ISSUE THREAD

**Issue by nitinjainsj** [pachyderm/pachyderm#5535]
There are a few defaults that need to change with 2.0

- [x] Remove coefficient config
- [x] remove --reverse option #5529 
- [x] remove --isS3V2 option (deprecated in 1.11.0)
- [x] ~~revisit resource defaults and options (standby == true by default)~~
- [x] ~~revisit init container resources (GPU requests?)~~

Issues related to removing Docker:

- [x] ~~https://github.com/pachyderm/pachyderm/issues/5928~~

cc @jdoliner @JoeyZwicker

**Comment by msteffen** [comment]
Possibly removing streaming RPCs and updating auth APIs: https://github.com/pachyderm/pachyderm/issues/5485

**Comment by JoeyZwicker** [comment]
enable_stats on by default would be good IMO -- as long as we don't store the logs in the stats commit anymore. 

Do we have a default logging that we can put in place? That's one general piece of feedback that came from Rad.ai (to be discussed further in Product sync) is that they wanted Pachyderm to come a bit more fully baked by default -- kind of "batteries included but swappable" instead of batteries not included.

cc @mindthevirt if you can think of anything else that comes up for 2.0 default changes.

**Comment by mindthevirt** [comment]
As part of 2.0, we should also remove all dependencies on Docker. Currently, we reference the docker socket, docker volumes etc in our auto-generated manifests. Since Kuberentes is going to switch from Docker to CRI. By doing the above, we'll also be able to support Fargate.

**Comment by JoeyZwicker** [comment]
Apologize if this doesnt fit nicely for this issue -- we can break it out into a separate issue if needed.

I think `pachctl shell` gets relatively low usage because most users don't know it exists, but it can improve the pachyderm onboarding experience significantly. Would we ever consider some way of letting users leverage shell by default? Or maybe it's something they can turn on by default in their pachctl config? To make this work nicely, there may need to be a few improvements to shell such as allowing kubectl and docker cmds to still work within the shell.

**Comment by echohack** [comment]
AWS Fargate support Ref: https://github.com/pachyderm/pachyderm/issues/4522

**Comment by nitinjainsj** [comment]
Adding a few more to track here... #6056 #6058 #6059

**Comment by actgardner** [comment]
> As part of 2.0, we should also remove all dependencies on Docker. Currently, we reference the docker socket, docker volumes etc in our auto-generated manifests. Since Kuberentes is going to switch from Docker to CRI. By doing the above, we'll also be able to support Fargate.

I think this is a reference to that fact that in 1.x we mount the host docker socket into the user container by default (which can be disabled with `--no-expose-docker-socket`)? I agree this isn't a great default, is the change just to not mount the socket in 2.0? I'm not sure what references to Docker volumes exist in our deployments?

**Comment by nitinjainsj** [comment]
All 2.0 misc changes that are listed in this tracking doc have been handled.

Except:
- #6058 #6059 (post 2.0)
- Fargate support is not planned yet (post 2.0)
